# Generated by Django 4.2.30 on 2026-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=32, unique=True)),
                ('character_template', models.JSONField()),
            ],
            options={
                'db_table': 'character_templates',
                'ordering': ['template_key'],
            },
        ),
    ]
