# Generated by Django 4.2.30 on 2026-07-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_users_from_auth'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnd_sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'dnd_session',
            },
        ),
        migrations.CreateModel(
            name='CharacterInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('template_json', models.JSONField()),
                ('dnd_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.dndsession')),
            ],
            options={
                'db_table': 'character_instance',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dndsession',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='one_active_dnd_session_per_user'),
        ),
    ]
