# Generated by Django 4.2.30 on 2026-07-06 20:42

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dndsession_characterinstance_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='WorldLore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('source_file', models.CharField(max_length=128)),
                ('section', models.CharField(max_length=200)),
                ('chunk_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('dnd_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_lore', to='core.dndsession')),
            ],
            options={
                'db_table': 'world_lore',
                'ordering': ['source_file', 'chunk_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='worldlore',
            constraint=models.UniqueConstraint(fields=('dnd_session', 'source_file', 'chunk_number'), name='unique_world_lore_chunk_per_session'),
        ),
    ]
