# Generated by Django 4.2.30 on 2026-07-06 20:59

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_worldlore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldLoreChunkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_key', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('source_file', models.CharField(max_length=128)),
                ('section', models.CharField(max_length=200)),
                ('chunk_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
            ],
            options={
                'db_table': 'world_lore_chunk_template',
                'ordering': ['source_file', 'chunk_number'],
                'indexes': [models.Index(fields=['scenario_key', 'active'], name='lore_template_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='worldlorechunktemplate',
            constraint=models.UniqueConstraint(fields=('scenario_key', 'version', 'source_file', 'chunk_number'), name='unique_world_lore_chunk_template'),
        ),
    ]
