# Generated by Django 4.2.30 on 2026-08-13 14:35

import copy
import uuid

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector


def _normalize_version(value):
    try:
        version = int(str(value).split(".", 1)[0])
    except (TypeError, ValueError) as exc:
        raise RuntimeError(f"Cannot migrate scenario version {value!r}.") from exc
    if version < 1:
        raise RuntimeError(f"Scenario version must be positive; received {value!r}.")
    return version


def _lore_title(source_file, metadata):
    return metadata.get("document_title") or source_file.rsplit("/", 1)[-1].rsplit(
        ".", 1
    )[0].replace("_", " ").title()


def _lore_visibility(metadata):
    if metadata.get("visibility") in {"player", "public_info"}:
        return "public_info"
    return "dm_only"


def backfill_combatless_campaign_schema(apps, schema_editor):
    CharacterInstance = apps.get_model("core", "CharacterInstance")
    DndSession = apps.get_model("core", "DndSession")
    WorldLore = apps.get_model("core", "WorldLore")
    WorldLoreChunkTemplate = apps.get_model("core", "WorldLoreChunkTemplate")

    characters = list(CharacterInstance.objects.all())
    for character in characters:
        character.mechanics_json = copy.deepcopy(character.template_json)
    if characters:
        CharacterInstance.objects.bulk_update(characters, ["mechanics_json"])

    templates = list(WorldLoreChunkTemplate.objects.all())
    for template in templates:
        metadata = template.metadata_json or {}
        template.version = str(_normalize_version(template.version))
        template.definition_uuid = uuid.uuid5(
            uuid.NAMESPACE_URL,
            (
                "ai-dungeon-master:"
                f"{template.scenario_key}:world_lore:{template.source_file}"
            ),
        )
        template.title = _lore_title(template.source_file, metadata)
        template.visibility = _lore_visibility(metadata)
        template.initially_known = template.visibility == "public_info"
    if templates:
        WorldLoreChunkTemplate.objects.bulk_update(
            templates,
            [
                "version",
                "definition_uuid",
                "title",
                "visibility",
                "initially_known",
            ],
        )

    template_by_source = {
        (
            template.scenario_key,
            _normalize_version(template.version),
            template.source_file,
            template.chunk_number,
        ): template
        for template in templates
    }

    sessions = list(DndSession.objects.all())
    session_by_id = {session.id: session for session in sessions}
    lore_rows = list(WorldLore.objects.all().order_by("id"))
    for lore in lore_rows:
        session = session_by_id[lore.dnd_session_id]
        version = _normalize_version(lore.version)
        session.scenario_version = version
        key = (
            session.scenario_key,
            version,
            lore.source_file,
            lore.chunk_number,
        )
        template = template_by_source.get(key)
        if template is None:
            metadata = lore.metadata or {}
            visibility = _lore_visibility(metadata)
            template = WorldLoreChunkTemplate.objects.create(
                definition_uuid=uuid.uuid5(
                    uuid.NAMESPACE_URL,
                    (
                        "ai-dungeon-master:"
                        f"{session.scenario_key}:world_lore:{lore.source_file}"
                    ),
                ),
                scenario_key=session.scenario_key,
                version=str(version),
                active=False,
                source_file=lore.source_file,
                title=_lore_title(lore.source_file, metadata),
                section=lore.section,
                chunk_number=lore.chunk_number,
                visibility=visibility,
                initially_known=visibility == "public_info",
                content=lore.content,
                metadata_json=metadata,
                embedding=lore.embedding,
            )
            template_by_source[key] = template
        elif template.content != lore.content:
            raise RuntimeError(
                "Legacy campaign lore differs from its source template for "
                f"{lore.source_file} chunk {lore.chunk_number}."
            )
        lore.template_id = template.id

    if sessions:
        DndSession.objects.bulk_update(sessions, ["scenario_version"])
    if lore_rows:
        WorldLore.objects.bulk_update(lore_rows, ["template"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worldlorechunktemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('model', models.CharField(max_length=100)),
                ('model_settings_json', models.JSONField(default=dict)),
                ('input_json', models.JSONField(default=dict)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('trace_json', models.JSONField(default=dict)),
                ('provider_trace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('validation_failure_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('error_json', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_run',
                'ordering': ['campaign_turn', 'run_number'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveBigIntegerField()),
                ('player_input', models.TextField()),
                ('dm_response_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign_turn',
                'ordering': ['dnd_session', 'turn_number'],
            },
        ),
        migrations.CreateModel(
            name='LocationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inaccessible', 'Inaccessible'), ('destroyed', 'Destroyed'), ('unknown', 'Unknown')], default='active', max_length=16)),
                ('state_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location_instance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LocationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_uuid', models.UUIDField()),
                ('scenario_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('source_file', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=160)),
                ('is_starting_location', models.BooleanField(default=False)),
                ('initially_known', models.BooleanField(default=False)),
                ('definition_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('metadata_json', models.JSONField(default=dict)),
                ('public_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('dm_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'location_template',
                'ordering': ['scenario_key', 'version', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NPCInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('dead', 'Dead'), ('departed', 'Departed')], default='active', max_length=16)),
                ('state_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'npc_instance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NPCTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_uuid', models.UUIDField()),
                ('scenario_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('source_file', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('initially_known', models.BooleanField(default=False)),
                ('definition_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('metadata_json', models.JSONField(default=dict)),
                ('public_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('dm_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'npc_template',
                'ordering': ['scenario_key', 'version', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('hidden', 'Hidden'), ('available', 'Available'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='hidden', max_length=16)),
                ('current_stage', models.PositiveIntegerField(default=0)),
                ('related_entities_json', models.JSONField(default=list)),
                ('state_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quest_instance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_uuid', models.UUIDField()),
                ('scenario_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('source_file', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('initial_status', models.CharField(choices=[('hidden', 'Hidden'), ('available', 'Available'), ('active', 'Active')], default='hidden', max_length=16)),
                ('initially_known', models.BooleanField(default=False)),
                ('definition_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('related_templates_json', models.JSONField(default=list)),
                ('metadata_json', models.JSONField(default=dict)),
                ('public_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('dm_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quest_template',
                'ordering': ['scenario_key', 'version', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RetrievedContextRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('source_type', models.CharField(choices=[('world_lore', 'World lore'), ('npc', 'NPC'), ('location', 'Location'), ('quest', 'Quest'), ('world_event', 'World event')], max_length=32)),
                ('source_id', models.BigIntegerField()),
                ('visibility', models.CharField(choices=[('public_info', 'Public info'), ('dm_only', 'DM only')], max_length=16)),
                ('content_snapshot', models.TextField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('initial_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rerank_score', models.FloatField(blank=True, null=True)),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('included_in_prompt', models.BooleanField(default=False)),
                ('exclusion_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_position', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'retrieved_context_record',
                'ordering': ['agent_run', 'initial_rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255)),
                ('sequence_number', models.PositiveIntegerField()),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments_json', models.JSONField(default=dict)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('error_json', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tool_call_record',
                'ordering': ['agent_run', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('related_entities_json', models.JSONField(default=list)),
                ('state_json', models.JSONField(default=core.models.empty_visibility_state)),
                ('importance', models.PositiveSmallIntegerField(default=3)),
                ('public_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('dm_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'world_event',
                'ordering': ['campaign_turn', 'sequence_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='worldlore',
            options={'ordering': ['template__source_file', 'template__chunk_number']},
        ),
        migrations.RemoveConstraint(
            model_name='worldlore',
            name='unique_world_lore_chunk_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='worldlorechunktemplate',
            name='unique_world_lore_chunk_template',
        ),
        migrations.RemoveIndex(
            model_name='worldlorechunktemplate',
            name='lore_template_active_idx',
        ),
        migrations.RenameField(
            model_name='worldlorechunktemplate',
            old_name='metadata',
            new_name='metadata_json',
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='mechanics_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='state_json',
            field=models.JSONField(default=core.models.empty_visibility_state),
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dndsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dndsession',
            name='scenario_key',
            field=models.CharField(default='whitesparrow', max_length=64),
        ),
        migrations.AddField(
            model_name='dndsession',
            name='scenario_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dndsession',
            name='state_json',
            field=models.JSONField(default=core.models.empty_visibility_state),
        ),
        migrations.AddField(
            model_name='dndsession',
            name='turn_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dndsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worldlore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldlore',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_lore', to='core.worldlorechunktemplate'),
        ),
        migrations.AddField(
            model_name='worldlorechunktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldlorechunktemplate',
            name='definition_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='worldlorechunktemplate',
            name='initially_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worldlorechunktemplate',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worldlorechunktemplate',
            name='visibility',
            field=models.CharField(choices=[('public_info', 'Public info'), ('dm_only', 'DM only')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='worldlorechunktemplate',
            name='source_file',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(
            backfill_combatless_campaign_schema,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='worldlore',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_lore', to='core.worldlorechunktemplate'),
        ),
        migrations.AlterField(
            model_name='worldlorechunktemplate',
            name='definition_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='worldlorechunktemplate',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='worldlorechunktemplate',
            name='visibility',
            field=models.CharField(choices=[('public_info', 'Public info'), ('dm_only', 'DM only')], max_length=16),
        ),
        migrations.AlterField(
            model_name='worldlorechunktemplate',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='chunk_number',
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='content',
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='section',
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='worldlore',
            name='version',
        ),
        migrations.AddIndex(
            model_name='dndsession',
            index=models.Index(fields=['scenario_key', 'scenario_version'], name='session_scenario_idx'),
        ),
        migrations.AddIndex(
            model_name='worldlorechunktemplate',
            index=models.Index(fields=['scenario_key', 'active', 'visibility'], name='lore_tpl_active_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='worldlore',
            constraint=models.UniqueConstraint(fields=('dnd_session', 'template'), name='uniq_session_lore_tpl'),
        ),
        migrations.AddConstraint(
            model_name='worldlorechunktemplate',
            constraint=models.UniqueConstraint(fields=('scenario_key', 'version', 'definition_uuid', 'chunk_number'), name='uniq_lore_tpl_chunk'),
        ),
        migrations.AddConstraint(
            model_name='worldlorechunktemplate',
            constraint=models.CheckConstraint(check=models.Q(('initially_known', False), ('visibility', 'public_info'), _connector='OR'), name='lore_known_public_ck'),
        ),
        migrations.AddField(
            model_name='worldevent',
            name='campaign_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_events', to='core.campaignturn'),
        ),
        migrations.AddField(
            model_name='worldevent',
            name='tool_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_events', to='core.toolcallrecord'),
        ),
        migrations.AddField(
            model_name='toolcallrecord',
            name='agent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='core.agentrun'),
        ),
        migrations.AddField(
            model_name='retrievedcontextrecord',
            name='agent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_context', to='core.agentrun'),
        ),
        migrations.AddIndex(
            model_name='questtemplate',
            index=models.Index(fields=['scenario_key', 'active'], name='quest_tpl_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='questtemplate',
            constraint=models.UniqueConstraint(fields=('scenario_key', 'version', 'definition_uuid'), name='uniq_quest_tpl_uuid'),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='dnd_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='core.dndsession'),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.questtemplate'),
        ),
        migrations.AddField(
            model_name='npctemplate',
            name='initial_location_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_npc_templates', to='core.locationtemplate'),
        ),
        migrations.AddField(
            model_name='npcinstance',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='core.locationinstance'),
        ),
        migrations.AddField(
            model_name='npcinstance',
            name='dnd_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='core.dndsession'),
        ),
        migrations.AddField(
            model_name='npcinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.npctemplate'),
        ),
        migrations.AddField(
            model_name='locationtemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_templates', to='core.locationtemplate'),
        ),
        migrations.AddField(
            model_name='locationinstance',
            name='dnd_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.dndsession'),
        ),
        migrations.AddField(
            model_name='locationinstance',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='core.locationinstance'),
        ),
        migrations.AddField(
            model_name='locationinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.locationtemplate'),
        ),
        migrations.AddField(
            model_name='campaignturn',
            name='dnd_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.dndsession'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='campaign_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.campaignturn'),
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.locationinstance'),
        ),
        migrations.AddField(
            model_name='dndsession',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focused_sessions', to='core.locationinstance'),
        ),
        migrations.AddIndex(
            model_name='worldevent',
            index=models.Index(fields=['event_type', 'created_at'], name='world_event_type_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='worldevent',
            constraint=models.UniqueConstraint(fields=('campaign_turn', 'sequence_number'), name='uniq_turn_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='worldevent',
            constraint=models.CheckConstraint(check=models.Q(('importance__gte', 1), ('importance__lte', 5)), name='world_event_importance_ck'),
        ),
        migrations.AddConstraint(
            model_name='toolcallrecord',
            constraint=models.UniqueConstraint(fields=('agent_run', 'call_id'), name='uniq_run_tool_call_id'),
        ),
        migrations.AddConstraint(
            model_name='toolcallrecord',
            constraint=models.UniqueConstraint(fields=('agent_run', 'sequence_number'), name='uniq_run_tool_sequence'),
        ),
        migrations.AddIndex(
            model_name='retrievedcontextrecord',
            index=models.Index(fields=['agent_run', 'included_in_prompt'], name='retrieved_run_included_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievedcontextrecord',
            index=models.Index(fields=['source_type', 'source_id'], name='retrieved_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='retrievedcontextrecord',
            constraint=models.CheckConstraint(check=models.Q(('source_id__gt', 0)), name='retrieved_source_id_ck'),
        ),
        migrations.AddIndex(
            model_name='questinstance',
            index=models.Index(fields=['dnd_session', 'status'], name='quest_session_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='questinstance',
            constraint=models.UniqueConstraint(fields=('dnd_session', 'template'), name='uniq_quest_instance_tpl'),
        ),
        migrations.AddIndex(
            model_name='npctemplate',
            index=models.Index(fields=['scenario_key', 'active'], name='npc_tpl_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='npctemplate',
            constraint=models.UniqueConstraint(fields=('scenario_key', 'version', 'definition_uuid'), name='uniq_npc_tpl_uuid'),
        ),
        migrations.AddIndex(
            model_name='npcinstance',
            index=models.Index(fields=['dnd_session', 'current_location', 'status'], name='npc_session_loc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='npcinstance',
            constraint=models.UniqueConstraint(fields=('dnd_session', 'template'), name='uniq_npc_instance_tpl'),
        ),
        migrations.AddIndex(
            model_name='locationtemplate',
            index=models.Index(fields=['scenario_key', 'active'], name='location_tpl_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationtemplate',
            constraint=models.UniqueConstraint(fields=('scenario_key', 'version', 'definition_uuid'), name='uniq_location_tpl_uuid'),
        ),
        migrations.AddConstraint(
            model_name='locationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_starting_location', True)), fields=('scenario_key', 'version'), name='uniq_start_location_tpl'),
        ),
        migrations.AddIndex(
            model_name='locationinstance',
            index=models.Index(fields=['dnd_session', 'status'], name='location_session_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationinstance',
            constraint=models.UniqueConstraint(fields=('dnd_session', 'template'), name='uniq_location_instance_tpl'),
        ),
        migrations.AddConstraint(
            model_name='campaignturn',
            constraint=models.UniqueConstraint(fields=('dnd_session', 'turn_number'), name='uniq_campaign_turn_number'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('campaign_turn', 'run_number'), name='uniq_turn_agent_run'),
        ),
    ]
