# Generated by Django 4.2.30 on 2026-08-13 16:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


def _relationship(relation, entity_type, entity_id):
    return {
        "relation": relation,
        "target": {"type": entity_type, "id": entity_id},
    }


def backfill_campaign_initialization_and_relationships(apps, schema_editor):
    CharacterInstance = apps.get_model("core", "CharacterInstance")
    DndSession = apps.get_model("core", "DndSession")
    LocationInstance = apps.get_model("core", "LocationInstance")
    LocationTemplate = apps.get_model("core", "LocationTemplate")
    NPCInstance = apps.get_model("core", "NPCInstance")
    NPCTemplate = apps.get_model("core", "NPCTemplate")
    QuestInstance = apps.get_model("core", "QuestInstance")
    QuestTemplate = apps.get_model("core", "QuestTemplate")
    WorldLore = apps.get_model("core", "WorldLore")
    WorldLoreChunkTemplate = apps.get_model("core", "WorldLoreChunkTemplate")

    location_templates = list(LocationTemplate.objects.all())
    for template in location_templates:
        template.relationships_json = []
        if template.parent_template_id:
            template.relationships_json.append(
                _relationship(
                    "contained_in",
                    "location",
                    template.parent_template_id,
                )
            )
    if location_templates:
        LocationTemplate.objects.bulk_update(
            location_templates,
            ["relationships_json"],
        )

    npc_templates = list(NPCTemplate.objects.all())
    for template in npc_templates:
        template.relationships_json = []
        if template.initial_location_template_id:
            template.relationships_json.append(
                _relationship(
                    "located_in",
                    "location",
                    template.initial_location_template_id,
                )
            )
    if npc_templates:
        NPCTemplate.objects.bulk_update(npc_templates, ["relationships_json"])

    quest_templates = list(QuestTemplate.objects.all())
    for template in quest_templates:
        template.relationships_json = [
            {
                "relation": "involves",
                "target": reference,
            }
            for reference in (template.relationships_json or [])
        ]
    if quest_templates:
        QuestTemplate.objects.bulk_update(quest_templates, ["relationships_json"])

    lore_templates = list(WorldLoreChunkTemplate.objects.all())
    for template in lore_templates:
        references = (template.metadata_json or {}).get("related_templates", [])
        template.relationships_json = [
            {
                "relation": "about",
                "target": reference,
            }
            for reference in references
        ]
    if lore_templates:
        WorldLoreChunkTemplate.objects.bulk_update(
            lore_templates,
            ["relationships_json"],
        )

    locations = list(LocationInstance.objects.all())
    for location in locations:
        if location.status in {"inaccessible", "unknown"}:
            location.status = "hidden"
        location.relationships_json = []
        if location.parent_location_id:
            location.relationships_json.append(
                _relationship(
                    "contained_in",
                    "location",
                    location.parent_location_id,
                )
            )
    if locations:
        LocationInstance.objects.bulk_update(
            locations,
            ["status", "relationships_json"],
        )

    npcs = list(NPCInstance.objects.all())
    for npc in npcs:
        if npc.status in {"missing", "departed"}:
            npc.status = "hidden"
        npc.relationships_json = []
        if npc.current_location_id:
            npc.relationships_json.append(
                _relationship("located_in", "location", npc.current_location_id)
            )
    if npcs:
        NPCInstance.objects.bulk_update(npcs, ["status", "relationships_json"])

    quests = list(QuestInstance.objects.all())
    for quest in quests:
        if quest.status in {"completed", "failed"}:
            quest.status = "finished"
        quest.relationships_json = [
            {
                "relation": "involves",
                "target": reference,
            }
            for reference in (quest.relationships_json or [])
        ]
    if quests:
        QuestInstance.objects.bulk_update(quests, ["status", "relationships_json"])

    characters = list(CharacterInstance.objects.all())
    for character in characters:
        character.relationships_json = []
        if character.current_location_id:
            character.relationships_json.append(
                _relationship(
                    "located_in",
                    "location",
                    character.current_location_id,
                )
            )
    if characters:
        CharacterInstance.objects.bulk_update(characters, ["relationships_json"])

    sessions = list(DndSession.objects.all())
    location_templates_by_session = {
        (instance.dnd_session_id, instance.template_id): instance.id
        for instance in locations
        if instance.template_id
    }
    npc_templates_by_session = {
        (instance.dnd_session_id, instance.template_id): instance.id
        for instance in npcs
        if instance.template_id
    }
    quest_templates_by_session = {
        (instance.dnd_session_id, instance.template_id): instance.id
        for instance in quests
        if instance.template_id
    }
    lore_rows = list(WorldLore.objects.all())
    lore_templates_by_session = {
        (instance.dnd_session_id, instance.template_id): instance.id
        for instance in lore_rows
    }
    runtime_maps = {
        "location": location_templates_by_session,
        "npc": npc_templates_by_session,
        "quest": quest_templates_by_session,
        "world_lore": lore_templates_by_session,
    }
    lore_template_by_id = {template.id: template for template in lore_templates}
    for lore in lore_rows:
        relationships = []
        template = lore_template_by_id.get(lore.template_id)
        for relationship in getattr(template, "relationships_json", []) or []:
            target = relationship.get("target", {})
            runtime_id = runtime_maps.get(target.get("type"), {}).get(
                (lore.dnd_session_id, target.get("id"))
            )
            if runtime_id:
                relationships.append(
                    _relationship(
                        relationship["relation"],
                        target["type"],
                        runtime_id,
                    )
                )
        lore.relationships_json = relationships
    if lore_rows:
        WorldLore.objects.bulk_update(lore_rows, ["relationships_json"])

    location_template_by_id = {template.id: template for template in location_templates}
    npc_template_by_id = {template.id: template for template in npc_templates}
    quest_template_by_id = {template.id: template for template in quest_templates}
    for session in sessions:
        known = {
            "locations": [],
            "npcs": [],
            "quests": [],
            "world_lore": [],
        }
        for location in locations:
            template = location_template_by_id.get(location.template_id)
            if (
                location.dnd_session_id == session.id
                and template
                and template.initially_known
            ):
                known["locations"].append(str(template.definition_uuid))
        for npc in npcs:
            template = npc_template_by_id.get(npc.template_id)
            if npc.dnd_session_id == session.id and template and template.initially_known:
                known["npcs"].append(str(template.definition_uuid))
        for quest in quests:
            template = quest_template_by_id.get(quest.template_id)
            if (
                quest.dnd_session_id == session.id
                and template
                and template.initially_known
            ):
                known["quests"].append(str(template.definition_uuid))
        for lore in lore_rows:
            template = lore_template_by_id.get(lore.template_id)
            if (
                lore.dnd_session_id == session.id
                and template
                and template.initially_known
            ):
                known["world_lore"].append(str(template.definition_uuid))
        session.status = "active" if session.active else "abandoned"
        session_quests = [
            quest for quest in quests if quest.dnd_session_id == session.id
        ]
        session_quests.sort(
            key=lambda quest: (
                {"active": 0, "available": 1}.get(quest.status, 2),
                quest.id,
            )
        )
        if session_quests:
            main_quest = session_quests[0]
            main_quest.status = "active"
            main_quest.save(update_fields=["status"])
            session.main_quest_id = main_quest.id
        else:
            session.main_quest_id = None
        session.initially_known_entities_json = {
            key: sorted(set(values)) for key, values in known.items()
        }
    if sessions:
        DndSession.objects.bulk_update(
            sessions,
            ["status", "main_quest", "initially_known_entities_json"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_agentrun_campaignturn_locationinstance_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dndsession",
            name="one_active_dnd_session_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="locationtemplate",
            name="uniq_start_location_tpl",
        ),
        migrations.RemoveConstraint(
            model_name="worldlorechunktemplate",
            name="lore_known_public_ck",
        ),
        migrations.RenameField(
            model_name="questinstance",
            old_name="related_entities_json",
            new_name="relationships_json",
        ),
        migrations.RenameField(
            model_name="questtemplate",
            old_name="related_templates_json",
            new_name="relationships_json",
        ),
        migrations.AddField(
            model_name="characterinstance",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="dndsession",
            name="initially_known_entities_json",
            field=models.JSONField(default=core.models.empty_initially_known_entities),
        ),
        migrations.AddField(
            model_name="dndsession",
            name="main_quest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_for_sessions",
                to="core.questinstance",
            ),
        ),
        migrations.AddField(
            model_name="dndsession",
            name="opening_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="dndsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="locationinstance",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="locationtemplate",
            name="initial_status",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("active", "Active"),
                    ("destroyed", "Destroyed"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="locationtemplate",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="npcinstance",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="npctemplate",
            name="initial_status",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("active", "Active"),
                    ("dead", "Dead"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="npctemplate",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="worldlore",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="worldlorechunktemplate",
            name="relationships_json",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(
            backfill_campaign_initialization_and_relationships,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="dndsession",
            name="active",
        ),
        migrations.RemoveField(
            model_name="locationtemplate",
            name="initially_known",
        ),
        migrations.RemoveField(
            model_name="locationtemplate",
            name="is_starting_location",
        ),
        migrations.RemoveField(
            model_name="npctemplate",
            name="initially_known",
        ),
        migrations.RemoveField(
            model_name="questtemplate",
            name="initially_known",
        ),
        migrations.RemoveField(
            model_name="worldlorechunktemplate",
            name="initially_known",
        ),
        migrations.AlterField(
            model_name="locationinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("active", "Active"),
                    ("destroyed", "Destroyed"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="npcinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("active", "Active"),
                    ("dead", "Dead"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("available", "Available"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                default="hidden",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questtemplate",
            name="initial_status",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("available", "Available"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                default="hidden",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="dndsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="one_active_dnd_session_per_user",
            ),
        ),
    ]
