# Generated by Django 4.2.30 on 2026-08-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deterministic_gameplay_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questinstance',
            old_name='current_stage',
            new_name='steps_completed',
        ),
        migrations.AlterField(
            model_name='questtemplate',
            name='initial_status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('available', 'Available'), ('active', 'Active')], default='hidden', max_length=16),
        ),
        migrations.CreateModel(
            name='QuestConditionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('quest_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.questtemplate')),
            ],
            options={
                'db_table': 'quest_condition_template',
                'ordering': ['quest_template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestConditionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_finished', 'Not finished'), ('finished', 'Finished')], default='not_finished', max_length=16)),
                ('finish_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.questinstance')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.questconditiontemplate')),
            ],
            options={
                'db_table': 'quest_condition_instance',
                'ordering': ['quest_instance', 'template__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='questconditiontemplate',
            constraint=models.UniqueConstraint(fields=('quest_template', 'order'), name='uniq_quest_condition_tpl_order'),
        ),
        migrations.AddConstraint(
            model_name='questconditioninstance',
            constraint=models.UniqueConstraint(fields=('quest_instance', 'template'), name='uniq_quest_condition_instance_tpl'),
        ),
        migrations.AddConstraint(
            model_name='questconditioninstance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('finish_text__isnull', True), ('status', 'not_finished')), models.Q(('finish_text__isnull', False), ('status', 'finished')), _connector='OR'), name='quest_condition_finish_text_ck'),
        ),
    ]
